
# Things for the Chombo makefile system. 
ebase    = main

#CHOMBO_HOME = /home/robertm/Projects/Chombo_3.2/lib

LibNames = EBAMRElliptic EBAMRTools Workshop EBTools AMRElliptic  AMRTools BoxTools

base_dir = .
src_dirs = ../../

include $(CHOMBO_HOME)/mk/Make.example
