name: Build and Deploy

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt install doxygen
          sudo apt install graphviz
          sudo apt install texlive
          sudo apt install texlive-latex-extra
          sudo apt install latexmk          
          python3 -m pip install sphinx sphinx_rtd_theme sphinxcontrib-bibtex
          python3 -m pip install -I docutils==0.16  # Downgrade docutils so that bullet points render properly with Sphinx
          
      - name: Build doxygen
        working-directory: ${{ github.workspace }}/Docs
        run: |
          doxygen doxyfile

      - name: Build HTML documentation
        working-directory: ${{ github.workspace }}/Docs/Sphinx        
        run: |
          cd Docs/Sphinx
          make html
          mv build/html/* ${{ github.workspace }}/Docs

      - name: Build PDF documentation
        working-directory: ${{ github.workspace }}/Docs/Sphinx
        run: |
          make latexpdf
          mv ebgeometry.pdf ${{ github.workspace }}/Docs
          
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'rmrsk/EBGeometry' && github.ref == 'refs/heads/main'        
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: Docs
          clean: false
