name: Code format

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-code-format
  cancel-in-progress: true

jobs:
  clang-format:
    if: github.event.pull_request.draft == false  
    name: clang-format
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang-format

      - name: Run clang-format
        if: always()        
        run: |
          find Source Examples \( -name "*.hpp" -o -name "*.cpp" \) -exec clang-format -i {} +

      - name: Check for modified files
        if: always()
        run: |
          git diff
          if [[ git diff-index --quiet HEAD == 0 ]]; then exit 0; else exit 1; fi

