name: EBGeometry Linux-GNU

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc    
  cancel-in-progress: true

jobs:
  GNU-DEBUG:
    if: github.event.pull_request.draft == false  
    name: Linux-GNU debug
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        comp: [g++-9, g++-10, g++-11]

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.comp }}

      - name: Compile DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()        
        run: |
          ${{ matrix.comp }} -std=c++14 \
          -pedantic -Wall -Wextra  -Wcast-align  -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 \
          -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast \
          -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel \
          -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused \
          main.cpp

      - name: Compile F18 example
        working-directory: Examples/EBGeometry_F18
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++17 \
          -pedantic -Wall -Wextra  -Wcast-align  -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 \
          -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast \
          -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel \
          -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused \
          main.cpp

      - name: Compile PackedSpheres example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 \
          -pedantic -Wall -Wextra  -Wcast-align  -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 \
          -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast \
          -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel \
          -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused \
          main.cpp

      - name: Compile RandomCity example
        working-directory: Examples/EBGeometry_RandomCity
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 \
          -pedantic -Wall -Wextra  -Wcast-align  -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 \
          -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast \
          -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel \
          -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused \
          main.cpp

      - name: Compile Shapes example
        working-directory: Examples/EBGeometry_Shapes
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 \
          -pedantic -Wall -Wextra  -Wcast-align  -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 \
          -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast \
          -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel \
          -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused \
          main.cpp

      - name: Run DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()        
        run: |
          ./a.out armadillo.stl
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run F18 example
        working-directory: Examples/EBGeometry_F18
        if: always()        
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi                              

      - name: Run PackedSpheres example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()        
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run RandomCity example
        working-directory: Examples/EBGeometry_RandomCity
        if: always()        
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run Shapes example
        working-directory: Examples/EBGeometry_Shapes
        if: always()        
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi                    

  GNU-OPT:
    if: github.event.pull_request.draft == false  
    name: Linux-GNU opt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        comp: [g++-9, g++-10, g++-11]
        std: [c++14]

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.comp }}

      - name: Compile DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()        
        run: |
          ${{ matrix.comp }} -std=c++14 -w -O3 main.cpp

      - name: Compile F18 example
        working-directory: Examples/EBGeometry_F18
        if: always()        
        run: |
          ${{ matrix.comp }} -std=c++17 -w -O3 main.cpp

      - name: Compile PackedSpheres example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 -w -O3 main.cpp

      - name: Compile RandomCity example
        working-directory: Examples/EBGeometry_RandomCity
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 -w -O3 main.cpp

      - name: Compile Shapes example
        working-directory: Examples/EBGeometry_RandomCity
        if: always()
        run: |
          ${{ matrix.comp }} -std=c++14 -w -O3 main.cpp

      - name: Run DCEL example
        working-directory: Examples/EBGeometry_DCEL
        run: |
          ./a.out armadillo.stl
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run F18 example
        working-directory: Examples/EBGeometry_F18
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi                                        

      - name: Run PackedSpheres example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run RandomCity example
        working-directory: Examples/EBGeometry_RandomCity
        if: always()
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Run Shapes example
        working-directory: Examples/EBGeometry_Shapes
        if: always()
        run: |
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi                              
