name: EBGeometry GNU

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc    
  cancel-in-progress: true

jobs:
  GNU:
    if: github.event.pull_request.draft == false  
    name: GNU
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        comp: [g++-7, g++-8, g++-9, g++-10]
        std: [c++14, c++17]
        opt: [-O3 -Wall, -O0 -Wall]

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.comp }}

      - name: DCEL
        working-directory: Examples/EBGeometry_DCEL
        run: |
          ${{ matrix.comp }} ${{ matrix.opt }} -std=${{ matrix.std }} main.cpp >& compile_log.txt
          echo compile_log.txt
          ./a.out porsche.ply

      - name: Union
        working-directory: Examples/EBGeometry_Union
        run: |
          ${{ matrix.comp }} ${{ matrix.opt }} -std=${{ matrix.std }} main.cpp                    
          ./a.out

