name: EBGeometry Linux-Intel

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-intel
  cancel-in-progress: true

jobs:
  Intel-OPT:
    if: github.event.pull_request.draft == false  
    name: Linux-Intel opt
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install Intel oneAPI
        working-directory: /tmp        
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic

      - name: Compile DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpc -std=c++14 -w -O3 main.cpp

      - name: Run DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh          
          ./a.out armadillo.stl
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi

      - name: Compile union example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh          
          icpc -std=c++14 -w -O3 main.cpp          

      - name: Run union example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh          
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          


  Intel-DEBUG:
    if: github.event.pull_request.draft == false  
    name: Linux-Intel debug
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout EBGeometry
        uses: actions/checkout@v2

      - name: Install Intel oneAPI
        working-directory: /tmp        
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic

      - name: Compile DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpc -std=c++14 -O0 \
          -Wall -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull \
          -Wparentheses -Wpointer-sign -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wunused-but-set-variable \
          -Wunused-variable -Wwrite-strings -Werror \
          main.cpp

      - name: Run DCEL example
        working-directory: Examples/EBGeometry_DCEL
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh
          ./a.out armadillo.stl
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          

      - name: Compile union example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpc -std=c++14 -O0 \
          -Wall -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull \
          -Wparentheses -Wpointer-sign -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wunused-but-set-variable \
          -Wunused-variable -Wwrite-strings -Werror \
          main.cpp

      - name: Run union example
        working-directory: Examples/EBGeometry_PackedSpheres
        if: always()
        run: |
          source /opt/intel/oneapi/setvars.sh
          ./a.out
          if [[ $? == 0 ]]; then exit 0; else exit 1; fi          
